// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1GUrWg3qlG5R1PiiZadxJqQGyE97FndA',
    appId: '1:79444646928:web:a9f9fe4088c7b60afbbe95',
    messagingSenderId: '79444646928',
    projectId: 'chatapp-with-firebase-35e7e',
    authDomain: 'chatapp-with-firebase-35e7e.firebaseapp.com',
    storageBucket: 'chatapp-with-firebase-35e7e.appspot.com',
    measurementId: 'G-TRQZ8H1ERC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkLDLTaGVdxD7Ewi1OCtrg1o8OvyVEdyc',
    appId: '1:79444646928:android:5396d8fc4f3eaaeafbbe95',
    messagingSenderId: '79444646928',
    projectId: 'chatapp-with-firebase-35e7e',
    storageBucket: 'chatapp-with-firebase-35e7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE-xxM8mpDirfcAPq5ApWv4soaWETeq9Y',
    appId: '1:79444646928:ios:4a58a900bb7399e6fbbe95',
    messagingSenderId: '79444646928',
    projectId: 'chatapp-with-firebase-35e7e',
    storageBucket: 'chatapp-with-firebase-35e7e.appspot.com',
    iosBundleId: 'com.example.flutterChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE-xxM8mpDirfcAPq5ApWv4soaWETeq9Y',
    appId: '1:79444646928:ios:9e74b974169326a4fbbe95',
    messagingSenderId: '79444646928',
    projectId: 'chatapp-with-firebase-35e7e',
    storageBucket: 'chatapp-with-firebase-35e7e.appspot.com',
    iosBundleId: 'com.example.flutterChatapp.RunnerTests',
  );
}
